export enum ActionTypes {
  EVENT_GET_CONTENT = 'EVENT/GET_CONTENT',
  EVENT_SAVE_CONTENT = 'EVENT/SAVE_CONTENT',
  EVENT_GET_LIST = 'EVENT/GET_LIST',
  EVENT_CHANGE_LIST_PAGE = 'EVENT/CHANGE_LIST_PAGE',

  SCOUT_GET_CONTENT = 'SCOUT/GET_CONTENT',
  SCOUT_SAVE_CONTENT = 'SCOUT/SAVE_CONTENT',
  SCOUT_GET_LIST = 'SCOUT/GET_LIST',
  SCOUT_CHANGE_LIST_PAGE = 'SCOUT/CHANGE_LIST_PAGE',

  UNIT_GET_CONTENT = 'UNIT/GET_CONTENT',
  UNIT_SAVE_CONTENT = 'UNIT/SAVE_CONTENT',
  UNIT_GET_LIST = 'UNIT/GET_LIST',
  UNIT_CHANGE_LIST_PAGE = 'UNIT/CHANGE_LIST_PAGE',

  CHARACTER_GET_CONTENT = 'CHARACTER/GET_CONTENT',
  CHARACTER_SAVE_CONTENT = 'CHARACTER/SAVE_CONTENT',
  CHARACTER_GET_LIST = 'CHARACTER/GET_LIST',
  CHARACTER_CHANGE_LIST_PAGE = 'CHARACTER/CHANGE_LIST_PAGE',
  CHARACTER_GET_HISTORY = 'CHARACTER/GET_HISTORY',

  CARD_GET_CONTENT = 'CARD/GET_CONTENT',
  CARD_SAVE_CONTENT = 'CARD/SAVE_CONTENT',
  CARD_GET_LIST = 'CARD/GET_LIST',
  CARD_CHANGE_LIST_PAGE = 'CARD/CHANGE_LIST_PAGE',
}
