export enum ActionTypes {
  GET_ARTIST = 'GET_ARTIST',
  GET_ARTISTS = 'GET_ARTISTS',

  GET_WORKS = 'GET_WORKS',
  GET_SONG = 'GET_SONG',
  GET_SONGS = 'GET_SONGS',

  GET_LIVES = 'GET_LIVES',
  GET_LIVE = 'GET_LIVE',
}
